repos:
- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.4.3.9003
  hooks:
  - id: style-files
  - id: lintr
    args: [--warn_only]
  - id: readme-rmd-rendered
  - id: parsable-R
  - id: no-browser-statement
  - id: no-debug-statement
  - id: deps-in-desc
    args: [--allow_private_imports]
  - id: use-tidy-description
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.20.0
  hooks:
  - id: commitlint
    stages: [commit-msg]
