on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: matlab-check

jobs:
  matlab-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: >
            Statistics_and_Machine_Learning_Toolbox
            Curve_Fitting_Toolbox

      - name: Run demo script
        uses: matlab-actions/run-command@v2
        with:
          command: cd tests/testthat; test_illa

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: simulated-data-results
          path: tests/testthat/test_illa_matlab_*.csv
